"use strict";
const yargs = require("yargs");
const Koa = require("koa");
const Router = require("koa-router");
const argv = yargs.argv;
const PORT = process.env.PORT || argv.port || 8383;
const HOST = process.env.HOST || argv.host || '0.0.0.0';
const app = new Koa();
const router = new Router();
app.use(router.routes());
app.use(router.allowedMethods());
const wechat_1 = require("./wechat");
const routes_1 = require("./routes");
routes_1.route(router, wechat_1.WechatController);
routes_1.route(router, wechat_1.TestController);
app.listen(PORT, HOST);
console.log(`Listening at ${HOST}:${PORT}`);
