var uuid = require('uuid/v4');

function id() {
  return uuid().replace(/-/g, '');
}

var ids = [];

for (var i = 0; i < 14; i++) {
  ids.push(id());
}

exports.seed = function(knex, Promise) {
  return Promise.all([
    knex('t_product_category').insert({id: ids[0], name: '美食', icon: 'http://www.crowdnear.com/m2/assets/images/product_category/ms.png', parentId: '', sort: 10}),
    knex('t_product_category').insert({id: ids[1], name: '丽人', icon: 'http://www.crowdnear.com/m2/assets/images/product_category/lr.png', parentId: '', sort: 20}),
    knex('t_product_category').insert({id: ids[2], name: '购物', icon: 'http://www.crowdnear.com/m2/assets/images/product_category/gw.png', parentId: '', sort: 30}),
    knex('t_product_category').insert({id: ids[3], name: '亲子', icon: 'http://www.crowdnear.com/m2/assets/images/product_category/qz.png', parentId: '', sort: 40}),
    knex('t_product_category').insert({id: ids[4], name: '生活服务', icon: 'http://www.crowdnear.com/m2/assets/images/product_category/shfw.png', parentId: '', sort: 50}),
    knex('t_product_category').insert({id: ids[5], name: '家装', icon: 'http://www.crowdnear.com/m2/assets/images/product_category/jz.png', parentId: '', sort: 60}),
    knex('t_product_category').insert({id: ids[6], name: '休闲娱乐', icon: 'http://www.crowdnear.com/m2/assets/images/product_category/xxyl.png', parentId: '', sort: 70}),
    knex('t_product_category').insert({id: ids[7], name: '学习培训', icon: 'http://www.crowdnear.com/m2/assets/images/product_category/xxpx.png', parentId: '', sort: 80}),
    knex('t_product_category').insert({id: ids[8], name: '运动', icon: 'http://www.crowdnear.com/m2/assets/images/product_category/yd.png', parentId: '', sort: 90}),
    knex('t_product_category').insert({id: ids[9], name: '健康', icon: 'http://www.crowdnear.com/m2/assets/images/product_category/jk.png', parentId: '', sort: 100}),
    knex('t_product_category').insert({id: ids[10], name: '周边游', icon: 'http://www.crowdnear.com/m2/assets/product_category/zby.png', parentId: '', sort: 110}),
    knex('t_product_category').insert({id: ids[11], name: '周边住', icon: 'http://www.crowdnear.com/m2/assets/product_category/zbz.png', parentId: '', sort: 120}),
    knex('t_product_category').insert({id: ids[12], name: '婚庆', icon: 'http://www.crowdnear.com/m2/assets/product_category/hq.png', parentId: '', sort: 130}),
    knex('t_product_category').insert({id: ids[13], name: '中介', icon: 'http://www.crowdnear.com/m2/assets/product_category/zj.png', parentId: '', sort: 140}),

    // 子项
    knex('t_product_category').insert({id: id(), name: '快餐简餐', icon: '', parentId: ids[0], sort: 10}),
    knex('t_product_category').insert({id: id(), name: '面包甜点', icon: '', parentId: ids[0], sort: 20}),
    knex('t_product_category').insert({id: id(), name: '小吃店', icon: '', parentId: ids[0], sort: 30}),
    knex('t_product_category').insert({id: id(), name: '大排档', icon: '', parentId: ids[0], sort: 40}),
    knex('t_product_category').insert({id: id(), name: '自助餐', icon: '', parentId: ids[0], sort: 50}),
    knex('t_product_category').insert({id: id(), name: '西餐', icon: '', parentId: ids[0], sort: 60}),
    knex('t_product_category').insert({id: id(), name: '海鲜', icon: '', parentId: ids[0], sort: 70}),
    knex('t_product_category').insert({id: id(), name: '素食', icon: '', parentId: ids[0], sort: 80}),
    knex('t_product_category').insert({id: id(), name: '火锅', icon: '', parentId: ids[0], sort: 90}),
    knex('t_product_category').insert({id: id(), name: '烧烤', icon: '', parentId: ids[0], sort: 100}),
    knex('t_product_category').insert({id: id(), name: '闽菜', icon: '', parentId: ids[0], sort: 110}),
    knex('t_product_category').insert({id: id(), name: '川菜', icon: '', parentId: ids[0], sort: 120}),
    knex('t_product_category').insert({id: id(), name: '湘菜', icon: '', parentId: ids[0], sort: 130}),
    knex('t_product_category').insert({id: id(), name: '粤菜', icon: '', parentId: ids[0], sort: 140}),
    knex('t_product_category').insert({id: id(), name: '江浙菜', icon: '', parentId: ids[0], sort: 150}),
    knex('t_product_category').insert({id: id(), name: '东北菜', icon: '', parentId: ids[0], sort: 160}),
    knex('t_product_category').insert({id: id(), name: '私家菜', icon: '', parentId: ids[0], sort: 170}),
    knex('t_product_category').insert({id: id(), name: '农家菜', icon: '', parentId: ids[0], sort: 180}),
    knex('t_product_category').insert({id: id(), name: '其他', icon: '', parentId: ids[0], sort: 190}),

    // 子项
    knex('t_product_category').insert({id: id(), name: '美发', icon: '', parentId: ids[1], sort: 10}),
    knex('t_product_category').insert({id: id(), name: '美容美体', icon: '', parentId: ids[1], sort: 20}),
    knex('t_product_category').insert({id: id(), name: '美甲美睫', icon: '', parentId: ids[1], sort: 30}),
    knex('t_product_category').insert({id: id(), name: '纤体瘦身', icon: '', parentId: ids[1], sort: 40}),
    knex('t_product_category').insert({id: id(), name: '整形', icon: '', parentId: ids[1], sort: 50}),
    knex('t_product_category').insert({id: id(), name: '祛痘', icon: '', parentId: ids[1], sort: 60}),
    knex('t_product_category').insert({id: id(), name: '舞蹈', icon: '', parentId: ids[1], sort: 70}),
    knex('t_product_category').insert({id: id(), name: '瑜伽', icon: '', parentId: ids[1], sort: 80}),
    knex('t_product_category').insert({id: id(), name: '纹身', icon: '', parentId: ids[1], sort: 90}),
    knex('t_product_category').insert({id: id(), name: '化妆品', icon: '', parentId: ids[1], sort: 100}),
    knex('t_product_category').insert({id: id(), name: '其他', icon: '', parentId: ids[1], sort: 110}),

    // 子项
    knex('t_product_category').insert({id: id(), name: '超市', icon: '', parentId: ids[2], sort: 10}),
    knex('t_product_category').insert({id: id(), name: '商场', icon: '', parentId: ids[2], sort: 20}),
    knex('t_product_category').insert({id: id(), name: '便利店', icon: '', parentId: ids[2], sort: 30}),
    knex('t_product_category').insert({id: id(), name: '食杂店', icon: '', parentId: ids[2], sort: 40}),
    knex('t_product_category').insert({id: id(), name: '米面粮油', icon: '', parentId: ids[2], sort: 50}),
    knex('t_product_category').insert({id: id(), name: '蔬菜肉蛋', icon: '', parentId: ids[2], sort: 60}),
    knex('t_product_category').insert({id: id(), name: '土特产', icon: '', parentId: ids[2], sort: 70}),
    knex('t_product_category').insert({id: id(), name: '水产', icon: '', parentId: ids[2], sort: 80}),
    knex('t_product_category').insert({id: id(), name: '水果', icon: '', parentId: ids[2], sort: 90}),
    knex('t_product_category').insert({id: id(), name: '烟酒行', icon: '', parentId: ids[2], sort: 100}),
    knex('t_product_category').insert({id: id(), name: '服装鞋帽', icon: '', parentId: ids[2], sort: 110}),
    knex('t_product_category').insert({id: id(), name: '箱包皮草', icon: '', parentId: ids[2], sort: 120}),
    knex('t_product_category').insert({id: id(), name: '家具', icon: '', parentId: ids[2], sort: 130}),
    knex('t_product_category').insert({id: id(), name: '家纺', icon: '', parentId: ids[2], sort: 140}),
    knex('t_product_category').insert({id: id(), name: '其他', icon: '', parentId: ids[2], sort: 150}),

    // 子项
    knex('t_product_category').insert({id: id(), name: '孕产护理', icon: '', parentId: ids[3], sort: 10}),
    knex('t_product_category').insert({id: id(), name: '早教中心', icon: '', parentId: ids[3], sort: 20}),
    knex('t_product_category').insert({id: id(), name: '幼儿教育', icon: '', parentId: ids[3], sort: 30}),
    knex('t_product_category').insert({id: id(), name: '幼儿才艺', icon: '', parentId: ids[3], sort: 40}),
    knex('t_product_category').insert({id: id(), name: '托儿所', icon: '', parentId: ids[3], sort: 50}),
    knex('t_product_category').insert({id: id(), name: '幼儿园', icon: '', parentId: ids[3], sort: 60}),
    knex('t_product_category').insert({id: id(), name: '婴童服饰', icon: '', parentId: ids[3], sort: 70}),
    knex('t_product_category').insert({id: id(), name: '婴童洗护', icon: '', parentId: ids[3], sort: 80}),
    knex('t_product_category').insert({id: id(), name: '婴童食品', icon: '', parentId: ids[3], sort: 90}),
    knex('t_product_category').insert({id: id(), name: '婴童用品', icon: '', parentId: ids[3], sort: 100}),
    knex('t_product_category').insert({id: id(), name: '玩具', icon: '', parentId: ids[3], sort: 110}),
    knex('t_product_category').insert({id: id(), name: '文具', icon: '', parentId: ids[3], sort: 120}),
    knex('t_product_category').insert({id: id(), name: '亲子摄影', icon: '', parentId: ids[3], sort: 130}),
    knex('t_product_category').insert({id: id(), name: '亲子玩乐', icon: '', parentId: ids[3], sort: 140}),
    knex('t_product_category').insert({id: id(), name: '其他', icon: '', parentId: ids[3], sort: 150}),

    // 子项
    knex('t_product_category').insert({id: id(), name: '洗衣', icon: '', parentId: ids[4], sort: 10}),
    knex('t_product_category').insert({id: id(), name: '洗车', icon: '', parentId: ids[4], sort: 20}),
    knex('t_product_category').insert({id: id(), name: '搬家', icon: '', parentId: ids[4], sort: 30}),
    knex('t_product_category').insert({id: id(), name: '租车', icon: '', parentId: ids[4], sort: 40}),
    knex('t_product_category').insert({id: id(), name: '管道疏通', icon: '', parentId: ids[4], sort: 50}),
    knex('t_product_category').insert({id: id(), name: '房屋修缮', icon: '', parentId: ids[4], sort: 60}),
    knex('t_product_category').insert({id: id(), name: '家庭保洁', icon: '', parentId: ids[4], sort: 70}),
    knex('t_product_category').insert({id: id(), name: '皮革翻新', icon: '', parentId: ids[4], sort: 80}),
    knex('t_product_category').insert({id: id(), name: '空调清洗', icon: '', parentId: ids[4], sort: 90}),
    knex('t_product_category').insert({id: id(), name: '灯具清洗', icon: '', parentId: ids[4], sort: 100}),
    knex('t_product_category').insert({id: id(), name: '水电维修', icon: '', parentId: ids[4], sort: 110}),
    knex('t_product_category').insert({id: id(), name: '家电维修', icon: '', parentId: ids[4], sort: 120}),
    knex('t_product_category').insert({id: id(), name: '电脑维修', icon: '', parentId: ids[4], sort: 130}),
    knex('t_product_category').insert({id: id(), name: '数码维修', icon: '', parentId: ids[4], sort: 140}),
    knex('t_product_category').insert({id: id(), name: '汽车维修', icon: '', parentId: ids[4], sort: 150}),
    knex('t_product_category').insert({id: id(), name: '汽车美容', icon: '', parentId: ids[4], sort: 160}),
    knex('t_product_category').insert({id: id(), name: '照相冲印', icon: '', parentId: ids[4], sort: 170}),
    knex('t_product_category').insert({id: id(), name: '打字复印', icon: '', parentId: ids[4], sort: 180}),
    knex('t_product_category').insert({id: id(), name: '鲜花', icon: '', parentId: ids[4], sort: 190}),
    knex('t_product_category').insert({id: id(), name: '眼镜', icon: '', parentId: ids[4], sort: 200}),
    knex('t_product_category').insert({id: id(), name: '其他', icon: '', parentId: ids[4], sort: 210}),

    // 子项
    knex('t_product_category').insert({id: id(), name: '装修设计', icon: '', parentId: ids[5], sort: 10}),
    knex('t_product_category').insert({id: id(), name: '家装卖场', icon: '', parentId: ids[5], sort: 20}),
    knex('t_product_category').insert({id: id(), name: '厨房卫浴', icon: '', parentId: ids[5], sort: 30}),
    knex('t_product_category').insert({id: id(), name: '装修建材', icon: '', parentId: ids[5], sort: 40}),
    knex('t_product_category').insert({id: id(), name: '家用电器', icon: '', parentId: ids[5], sort: 50}),
    knex('t_product_category').insert({id: id(), name: '家具家居', icon: '', parentId: ids[5], sort: 60}),
    knex('t_product_category').insert({id: id(), name: '土工', icon: '', parentId: ids[5], sort: 70}),
    knex('t_product_category').insert({id: id(), name: '水电工', icon: '', parentId: ids[5], sort: 80}),
    knex('t_product_category').insert({id: id(), name: '木工', icon: '', parentId: ids[5], sort: 90}),
    knex('t_product_category').insert({id: id(), name: '油漆工', icon: '', parentId: ids[5], sort: 100}),
    knex('t_product_category').insert({id: id(), name: '其他', icon: '', parentId: ids[5], sort: 110}),

    // 子项
    knex('t_product_category').insert({id: id(), name: '茶馆', icon: '', parentId: ids[6], sort: 10}),
    knex('t_product_category').insert({id: id(), name: '酒吧', icon: '', parentId: ids[6], sort: 20}),
    knex('t_product_category').insert({id: id(), name: '咖啡店', icon: '', parentId: ids[6], sort: 30}),
    knex('t_product_category').insert({id: id(), name: '棋牌室', icon: '', parentId: ids[6], sort: 40}),
    knex('t_product_category').insert({id: id(), name: '电影院', icon: '', parentId: ids[6], sort: 50}),
    knex('t_product_category').insert({id: id(), name: '图书馆', icon: '', parentId: ids[6], sort: 60}),
    knex('t_product_category').insert({id: id(), name: '网吧网咖', icon: '', parentId: ids[6], sort: 70}),
    knex('t_product_category').insert({id: id(), name: '游乐游艺', icon: '', parentId: ids[6], sort: 80}),
    knex('t_product_category').insert({id: id(), name: '手工坊', icon: '', parentId: ids[6], sort: 90}),
    knex('t_product_category').insert({id: id(), name: '宠物店', icon: '', parentId: ids[6], sort: 100}),
    knex('t_product_category').insert({id: id(), name: '推拿按摩', icon: '', parentId: ids[6], sort: 110}),
    knex('t_product_category').insert({id: id(), name: '足浴指压', icon: '', parentId: ids[6], sort: 120}),
    knex('t_product_category').insert({id: id(), name: '拔罐', icon: '', parentId: ids[6], sort: 130}),
    knex('t_product_category').insert({id: id(), name: '刮痧', icon: '', parentId: ids[6], sort: 140}),
    knex('t_product_category').insert({id: id(), name: 'SPA', icon: '', parentId: ids[6], sort: 150}),
    knex('t_product_category').insert({id: id(), name: '精油', icon: '', parentId: ids[6], sort: 160}),
    knex('t_product_category').insert({id: id(), name: '其他', icon: '', parentId: ids[6], sort: 170}),

    // 子项
    knex('t_product_category').insert({id: id(), name: '小学辅导', icon: '', parentId: ids[7], sort: 10}),
    knex('t_product_category').insert({id: id(), name: '初中辅导', icon: '', parentId: ids[7], sort: 20}),
    knex('t_product_category').insert({id: id(), name: '高中辅导', icon: '', parentId: ids[7], sort: 30}),
    knex('t_product_category').insert({id: id(), name: '作文', icon: '', parentId: ids[7], sort: 40}),
    knex('t_product_category').insert({id: id(), name: '演讲', icon: '', parentId: ids[7], sort: 50}),
    knex('t_product_category').insert({id: id(), name: '外语', icon: '', parentId: ids[7], sort: 60}),
    knex('t_product_category').insert({id: id(), name: '音乐', icon: '', parentId: ids[7], sort: 70}),
    knex('t_product_category').insert({id: id(), name: '美术', icon: '', parentId: ids[7], sort: 80}),
    knex('t_product_category').insert({id: id(), name: '美容化妆', icon: '', parentId: ids[7], sort: 90}),
    knex('t_product_category').insert({id: id(), name: '会计', icon: '', parentId: ids[7], sort: 100}),
    knex('t_product_category').insert({id: id(), name: '电脑', icon: '', parentId: ids[7], sort: 110}),
    knex('t_product_category').insert({id: id(), name: '厨艺', icon: '', parentId: ids[7], sort: 120}),
    knex('t_product_category').insert({id: id(), name: '驾校', icon: '', parentId: ids[7], sort: 130}),
    knex('t_product_category').insert({id: id(), name: '留学', icon: '', parentId: ids[7], sort: 140}),
    knex('t_product_category').insert({id: id(), name: '其他', icon: '', parentId: ids[7], sort: 150}),

    // 子项
    knex('t_product_category').insert({id: id(), name: '体育馆', icon: '', parentId: ids[8], sort: 10}),
    knex('t_product_category').insert({id: id(), name: '健身房', icon: '', parentId: ids[8], sort: 20}),
    knex('t_product_category').insert({id: id(), name: '羽毛球', icon: '', parentId: ids[8], sort: 30}),
    knex('t_product_category').insert({id: id(), name: '乒乓球', icon: '', parentId: ids[8], sort: 40}),
    knex('t_product_category').insert({id: id(), name: '台球', icon: '', parentId: ids[8], sort: 50}),
    knex('t_product_category').insert({id: id(), name: '武术', icon: '', parentId: ids[8], sort: 60}),
    knex('t_product_category').insert({id: id(), name: '游泳', icon: '', parentId: ids[8], sort: 70}),
    knex('t_product_category').insert({id: id(), name: '舞蹈', icon: '', parentId: ids[8], sort: 80}),
    knex('t_product_category').insert({id: id(), name: '瑜伽', icon: '', parentId: ids[8], sort: 90}),
    knex('t_product_category').insert({id: id(), name: '太极', icon: '', parentId: ids[8], sort: 100}),
    knex('t_product_category').insert({id: id(), name: '体育用品', icon: '', parentId: ids[8], sort: 110}),
    knex('t_product_category').insert({id: id(), name: '钓具店', icon: '', parentId: ids[8], sort: 120}),
    knex('t_product_category').insert({id: id(), name: '其他', icon: '', parentId: ids[8], sort: 130}),

    // 子项
    knex('t_product_category').insert({id: id(), name: '医院', icon: '', parentId: ids[9], sort: 10}),
    knex('t_product_category').insert({id: id(), name: '诊所', icon: '', parentId: ids[9], sort: 20}),
    knex('t_product_category').insert({id: id(), name: '卫生服务站', icon: '', parentId: ids[9], sort: 30}),
    knex('t_product_category').insert({id: id(), name: '妇幼保健院', icon: '', parentId: ids[9], sort: 40}),
    knex('t_product_category').insert({id: id(), name: '药店', icon: '', parentId: ids[9], sort: 50}),
    knex('t_product_category').insert({id: id(), name: '体检中心', icon: '', parentId: ids[9], sort: 60}),
    knex('t_product_category').insert({id: id(), name: '口腔齿科', icon: '', parentId: ids[9], sort: 70}),
    knex('t_product_category').insert({id: id(), name: '医疗器械', icon: '', parentId: ids[9], sort: 80}),
    knex('t_product_category').insert({id: id(), name: '营养品', icon: '', parentId: ids[9], sort: 90}),
    knex('t_product_category').insert({id: id(), name: '保健品', icon: '', parentId: ids[9], sort: 100}),
    knex('t_product_category').insert({id: id(), name: '其他', icon: '', parentId: ids[9], sort: 110}),

    // 子项
    knex('t_product_category').insert({id: id(), name: '景点', icon: '', parentId: ids[10], sort: 10}),
    knex('t_product_category').insert({id: id(), name: '戏院', icon: '', parentId: ids[10], sort: 20}),
    knex('t_product_category').insert({id: id(), name: '温泉', icon: '', parentId: ids[10], sort: 30}),
    knex('t_product_category').insert({id: id(), name: '故居', icon: '', parentId: ids[10], sort: 40}),
    knex('t_product_category').insert({id: id(), name: '主题公园', icon: '', parentId: ids[10], sort: 50}),
    knex('t_product_category').insert({id: id(), name: '水上乐园', icon: '', parentId: ids[10], sort: 60}),
    knex('t_product_category').insert({id: id(), name: '动植物园', icon: '', parentId: ids[10], sort: 70}),
    knex('t_product_category').insert({id: id(), name: '海洋馆', icon: '', parentId: ids[10], sort: 80}),
    knex('t_product_category').insert({id: id(), name: '博物馆', icon: '', parentId: ids[10], sort: 90}),
    knex('t_product_category').insert({id: id(), name: '展览馆', icon: '', parentId: ids[10], sort: 100}),
    knex('t_product_category').insert({id: id(), name: '其他', icon: '', parentId: ids[10], sort: 110}),

    // 子项
    knex('t_product_category').insert({id: id(), name: '高端酒店', icon: '', parentId: ids[11], sort: 10}),
    knex('t_product_category').insert({id: id(), name: '主题酒店', icon: '', parentId: ids[11], sort: 20}),
    knex('t_product_category').insert({id: id(), name: '经济型酒店', icon: '', parentId: ids[11], sort: 30}),
    knex('t_product_category').insert({id: id(), name: '公寓型酒店', icon: '', parentId: ids[11], sort: 40}),
    knex('t_product_category').insert({id: id(), name: '青年旅社', icon: '', parentId: ids[11], sort: 50}),
    knex('t_product_category').insert({id: id(), name: '招待所', icon: '', parentId: ids[11], sort: 60}),
    knex('t_product_category').insert({id: id(), name: '宾馆', icon: '', parentId: ids[11], sort: 70}),
    knex('t_product_category').insert({id: id(), name: '客栈', icon: '', parentId: ids[11], sort: 80}),
    knex('t_product_category').insert({id: id(), name: '公寓民宿', icon: '', parentId: ids[11], sort: 90}),
    knex('t_product_category').insert({id: id(), name: '钟点房', icon: '', parentId: ids[11], sort: 100}),
    knex('t_product_category').insert({id: id(), name: '其他', icon: '', parentId: ids[11], sort: 110}),

    // 子项
    knex('t_product_category').insert({id: id(), name: '婚纱摄影', icon: '', parentId: ids[12], sort: 10}),
    knex('t_product_category').insert({id: id(), name: '个性写真', icon: '', parentId: ids[12], sort: 20}),
    knex('t_product_category').insert({id: id(), name: '婚礼跟拍', icon: '', parentId: ids[12], sort: 30}),
    knex('t_product_category').insert({id: id(), name: '彩妆造型', icon: '', parentId: ids[12], sort: 40}),
    knex('t_product_category').insert({id: id(), name: '婚纱礼服', icon: '', parentId: ids[12], sort: 50}),
    knex('t_product_category').insert({id: id(), name: '婚戒首饰', icon: '', parentId: ids[12], sort: 60}),
    knex('t_product_category').insert({id: id(), name: '西服定制', icon: '', parentId: ids[12], sort: 70}),
    knex('t_product_category').insert({id: id(), name: '婚车租赁', icon: '', parentId: ids[12], sort: 80}),
    knex('t_product_category').insert({id: id(), name: '婚庆公司', icon: '', parentId: ids[12], sort: 90}),
    knex('t_product_category').insert({id: id(), name: '司仪主持', icon: '', parentId: ids[12], sort: 100}),
    knex('t_product_category').insert({id: id(), name: '其他', icon: '', parentId: ids[12], sort: 110}),

    // 子项
    knex('t_product_category').insert({id: id(), name: '会计师事务', icon: '', parentId: ids[13], sort: 10}),
    knex('t_product_category').insert({id: id(), name: '律师事务', icon: '', parentId: ids[13], sort: 20}),
    knex('t_product_category').insert({id: id(), name: '房地产中介', icon: '', parentId: ids[13], sort: 30}),
    knex('t_product_category').insert({id: id(), name: '婚姻介绍', icon: '', parentId: ids[13], sort: 40}),
    knex('t_product_category').insert({id: id(), name: '税务代理', icon: '', parentId: ids[13], sort: 50}),
    knex('t_product_category').insert({id: id(), name: '专利商标', icon: '', parentId: ids[13], sort: 60}),
    knex('t_product_category').insert({id: id(), name: '金融保险证券', icon: '', parentId: ids[13], sort: 70}),
    knex('t_product_category').insert({id: id(), name: '商贸信息', icon: '', parentId: ids[13], sort: 80}),
    knex('t_product_category').insert({id: id(), name: '企业管理', icon: '', parentId: ids[13], sort: 90}),
    knex('t_product_category').insert({id: id(), name: '工程管理', icon: '', parentId: ids[13], sort: 100}),
    knex('t_product_category').insert({id: id(), name: '其他', icon: '', parentId: ids[13], sort: 110}),
  ]);
};
